remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: AI At Work
description: AI can give a helping hand in the work load of swifting through vast information when implemented as self-reflective RAG agents.
show_downloads: false
