remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gen AI using Spring Boot
description: LLM inferencing using Spring Boot & Headless architecture with Angular for the chat interface addresses both scalability and performance challenges of Self Reflective Agentic Gen AI applications.  
show_downloads: false
